employee.out: employee.cpp manager.cpp trainee.cpp employee_test.cpp engineer.cpp
	g++ employee.cpp manager.cpp engineer.cpp trainee.cpp employee_test.cpp -lgtest -lgtest_main -lpthread -o employee.out

test:
	./employee.out